# Site Settings
title: Multinerd
email: m.hedaitulla@live.com
description: >
  My Website
baseurl: ""
url: "http://multinerd.github.io"
#twitter_username: taniarascia
github_username:  multinerd
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']



# dependencies
highlighter: rouge

kramdown:
  auto_ids: true
  input: GFM

markdown: kramdown

# permalinks
permalink: pretty
